<?php

namespace ProjxIO\Container;

use PHPUnit_Framework_TestCase;

class ContainerCollectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Collection
     */
    private static $collection;

    /**
     * @var array
     */
    private static $items;

    /**
     * @inheritDoc
     */
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        self::$items  = ['a' => 'A'];
        self::$collection = new ContainerCollection(new ArrayReferenceContainer(self::$items));
    }

    public function testConstructor()
    {
        $this->assertEquals(self::$items, self::$collection->items());
    }
}
